TWITCH_ACCESS_TOKEN = "YOUR_ACCESS_TOKEN"
LOGIN_CHANNEL = "YOUR_CHANNEL"
COMMAND_PREFIX = "!"

# URL省略設定
ENABLE_URL_REPLACEMENT = True  # URL省略設定 Trueで省略, Falseで無効
URL_REPLACEMENT = " URL省略 " # 省略する際に変換する文字列